# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"0\n\x0cOrderRequest\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.suggestions.Item\" \n\rOrderRepsonse\x12\x0f\n\x07message\x18\x01 \x01(\t2X\n\x11SuggestionService\x12\x43\n\nSaySuggest\x12\x19.suggestions.OrderRequest\x1a\x1a.suggestions.OrderRepsonseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=34
  _globals['_ITEM']._serialized_end=72
  _globals['_ORDERREQUEST']._serialized_start=74
  _globals['_ORDERREQUEST']._serialized_end=122
  _globals['_ORDERREPSONSE']._serialized_start=124
  _globals['_ORDERREPSONSE']._serialized_end=156
  _globals['_SUGGESTIONSERVICE']._serialized_start=158
  _globals['_SUGGESTIONSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
