{
 "title": "Bookstore overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Checkouts" } },
  {
   "title": "Checkout traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "filters": [
      { "id": "f34e0b2b", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "checkout" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total orders accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "orders_accepted_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Total books ordered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "books_ordered_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Order sizes distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "order_sizes_bucket", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Request durations distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_durations_milliseconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "options": { "content": "# Order queue" } },
  {
   "title": "Orders queued (counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "orders_queued", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Orders queued (gauge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "orders_in_queue", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Max queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "max_queue_size", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Failed dequeues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "failed_dequeues_total", "legendFormat": "{{__name__}}" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 }, "options": { "content": "# Database" } },
  {
   "title": "Stored books",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "targets": [
    { "expr": "avg by(title) (stored_books)", "legendFormat": "__auto" }
   ]
  }
 ]
}