# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x05\x66raud\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"*\n\x0cOrderRequest\x12\x1a\n\x05items\x18\x01 \x03(\x0b\x32\x0b.fraud.Item\"2\n\rOrderRepsonse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2E\n\x0c\x46raudService\x12\x35\n\x08SayFraud\x12\x13.fraud.OrderRequest\x1a\x14.fraud.OrderRepsonseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=32
  _globals['_ITEM']._serialized_end=70
  _globals['_ORDERREQUEST']._serialized_start=72
  _globals['_ORDERREQUEST']._serialized_end=114
  _globals['_ORDERREPSONSE']._serialized_start=116
  _globals['_ORDERREPSONSE']._serialized_end=166
  _globals['_FRAUDSERVICE']._serialized_start=168
  _globals['_FRAUDSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
