# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x05queue\x1a\x0c\x63ommon.proto\"2\n\x0f\x45nqueueResponse\x12\x0e\n\x06\x66\x61iled\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x82\x01\n\x11OrderQueueService\x12;\n\x07\x45nqueue\x12\x18.common.ItemsInitRequest\x1a\x16.queue.EnqueueResponse\x12\x30\n\x05\x44\x65que\x12\r.common.Empty\x1a\x18.common.ItemsInitRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUERESPONSE']._serialized_start=42
  _globals['_ENQUEUERESPONSE']._serialized_end=92
  _globals['_ORDERQUEUESERVICE']._serialized_start=95
  _globals['_ORDERQUEUESERVICE']._serialized_end=225
# @@protoc_insertion_point(module_scope)
